#!/bin/sh

mkdir /var/run/memory
chmod 777 /var/run/memory

set -e


cp -a /opt/var/kdb/memory_init/memory/* /var/run/memory
#find /opt/var/kdb/memory_init/memory/ -type d -print0 | xargs -0 chsmack -t
touch /tmp/vconf-initialized
